#!/bin/bash
# based on: https://www.slingacademy.com/article/ubuntu-how-to-write-an-rsync-backup-script/

BACUP_DIR="$HOME/stuff/bacup"
SOURCE="$HOME"
DEST="$BACUP_DIR/$(date +"%Y_%m_%d__%H_%M_%S")"
CURRENT="$BACUP_DIR/current"
TAR_FILE="$BACUP_DIR/bacup.tar.gz"

EXLUCE="$BACUP_DIR/exclude.txt"
INCLUDE="$BACUP_DIR/include.txt"

LOG="$BACUP_DIR/bacup.log"
CMD_LOG="$BACUP_DIR/bacup_cmd.log"

[ -f "$EXLUCE" ]  || touch "$EXLUCE"
[ -f "$INCLUDE" ] || touch "$INCLUDE"
[ -f "$CMD_LOG" ] && echo "# bacup cmd log" > "$CMD_LOG"

# do bacup
echo "bacup: starting backup, $(date '+%Y-%m-%d %H:%M:%S')" | tee -a "$CMD_LOG"
rsync -avr --mkpath --hard-links -exclude="$BACUP_DIR" \
    --exclude-from="$EXLUCE" --include-from="$INCLUDE" \
    --link-dest="$CURRENT" "$SOURCE" "$DEST" 2>&1 | tee -a "$CMD_LOG"
status="${PIPESTATUS[0]}"

if [ "$status" -ne 0 ]; then
    echo "bacup: error during backup, $(date '+%Y-%m-%d %H:%M:%S'), check '$CMD_LOG'"
    echo "[$(date +"%Y/%m/%d_%H:%M:%S")] ERROR: rsync failed with exit code $status" >> "$LOG"
    herbe $'bacup\nerror' 

    exit "$status"
else
    echo "bacup: backup done, $(date '+%Y-%m-%d %H:%M:%S')"
    echo "[$(date +"%Y/%m/%d_%H:%M:%S")] OK   : rsync completed successfully." >> "$LOG"
fi

# update symlink to latest backup
[ -L "$CURRENT" ] && rm -f "$CURRENT"
echo -e "\n\nbacup: linkin..." | tee -a "$CMD_LOG"
ln -vs "$DEST" "$CURRENT" | tee -a "$CMD_LOG"
status="${PIPESTATUS[0]}"

if [ "$status" -ne 0 ]; then
    echo "bacup: error during linkin, $(date '+%Y-%m-%d %H:%M:%S'), check '$CMD_LOG'"
    echo "[$(date +"%Y/%m/%d_%H:%M:%S")] ERROR: linkin failed." >> "$LOG"
    herbe $'bacup\nerror'

    exit "$status"
else
    echo "bacup: linkin done, $(date '+%Y-%m-%d %H:%M:%S')"
    echo "[$(date +"%Y/%m/%d_%H:%M:%S")] OK   : linkin completed successfully." >> "$LOG"
fi

# zip latest backup
echo -e "\n\nbacup: tar-ing..." | tee -a "$CMD_LOG"

tar -czf "$TAR_FILE" -C "$BACUP_DIR" "$(basename "$DEST")" 2>&1 | tee -a "$CMD_LOG"
status="${PIPESTATUS[0]}"

if [ "$status" -ne 0 ]; then
    echo "bacup: error during compresion, $(date '+%Y-%m-%d %H:%M:%S'), check '$CMD_LOG'"
    echo "[$(date +"%Y/%m/%d_%H:%M:%S")] ERROR: compresion failed." >> "$LOG"
    herbe $'bacup\nerror'

    exit "$status"
else
    echo "bacup: compresion done, $(date '+%Y-%m-%d %H:%M:%S')"
    echo "[$(date +"%Y/%m/%d_%H:%M:%S")] OK   : compresion completed successfully." >> "$LOG"

    echo -e "\n\nbacup: result:"
    du -hs "$DEST" "$TAR_FILE"
fi

herbe $'bacup\ndone'
