#!/bin/bash

# Dirs
DIR_ORIGIN="/home/numen/"
DIR_BACKUPS="/var/backups/bacup"
TAR_NAME="bacup.tar.gz"
TAR_FILE="$DIR_BACKUPS/$TAR_NAME"

DIR_TODAY="$DIR_BACKUPS/$(date +"%Y-%m-%d")"
LIST_DIRS="$(find $DIR_BACKUPS -maxdepth 1 | rg "[0-9]{4}-[0-9]{2}-[0-9]{2}" | sort)"
DIR_LAST="$(echo "$LIST_DIRS" | tail -n 1)"

MAX_DIRS="16"
LEN_DIRS="$(echo -e "$LIST_DIRS" | wc -l)"
OLD_DIRS="$(echo -e "$LIST_DIRS" | head -n $((LEN_DIRS - MAX_DIRS)))"
OLD_DIR_NAMES="$(echo -e "$OLD_DIRS" | sed -e "s|$DIR_BACKUPS||" | tr '\n' ' ' | sed -e "s| $||")"

LOG_FILE="$DIR_BACKUPS/bacup.log"

# Prog
[ 1 -ne $# ] && \
    echo "bacup: only one flag must be passed (-i, -a)" 1>&2 && \
    exit 1
if ! sudo -nv 2> /dev/null; then
    echo "bacup: Permission denien" 1>&2 && \
    exit 1
fi

if [ "-i" = "$1" ]; then
    [ "$MAX_DIRS" -lt "$LEN_DIRS" ] && \
        sudo rm -rfd $OLD_DIRS && \
        sudo easylog "$LOG_FILE" 0 "deleted old, dir(s) ($OLD_DIR_NAMES)."

    if [ -z "$DIR_LAST" ]; then  # first bacup
        DIR_LAST="$DIR_TODAY"
        sudo mkdir "$DIR_TODAY"
    elif [ "$DIR_TODAY" = "$DIR_LAST" ]; then  # today we already did one
        sudo rm -rfd "$DIR_TODAY"
        sudo easylog "$LOG_FILE" 0 "cleaned todays inc. backup ($DIR_TODAY)."
        DIR_LAST="$(echo "$LIST_DIRS" | tail -n 2 | head -n 1)" # use the previous day
    fi

    sudo rsync -av \
        --exclude="$TAR_NAME" \
        --exclude="*/.git" \
        --exclude=".cache" \
        --exclude=".cargo" \
        --exclude=".eclipse" \
        --exclude=".gnupg" \
        --exclude=".java" \
        --exclude=".local/share" \
        --exclude=".local/state" \
        --exclude=".npm" \
        --exclude=".p2" \
        --exclude=".swt" \
        --exclude="snap" \
        --exclude="stuff/.dotfiles" \
        --exclude="stuff/Downloads" \
        --exclude="stuff/eclipse" \
        --exclude="stuff/eclipse-workspace/.metadata" \
        --exclude="stuff/ehes/weka" \
        --exclude="stuff/shit" \
        --exclude="wekafiles" \
        --link-dest="$DIR_LAST" \
        "$DIR_ORIGIN" "$DIR_TODAY" && \
    sudo easylog "$LOG_FILE" 0 "incremental bacup made." && \
    notify-send --urgency=normal -t 3000 -i "terminal" "incremental bacup made. ミᕕ(   ᐛ   ) ᕗ" && \
    exit 0
fi

echo "$DIR_LAST"

[ "-a" = "$1" ] && \
    sudo tar -czvf "$TAR_FILE" --directory="$DIR_LAST" . && \
    notify-send --urgency=normal -t 3000 -i "terminal" "bacup made. ミᕕ(   ᐛ   ) ᕗ" && \
    exit 0

echo "bacup: invalid flag" 1>&2
exit 1
