#!/bin/sh

PROGRAMS="  st\n󱝆  surf\n  firefox\n  zathura\n  powermenu\n  screenshot\n  bacup\n"
SELECTOR="dmenu -c -l $(printf "%b" "$PROGRAMS" | wc -l) $*"

RESULT="$(printf "%b" "$PROGRAMS" | $SELECTOR)"
RESULT="${RESULT##* }"

[ "$RESULT" ] && $RESULT

