#!/bin/bash

#DEFAULT_TERM_BG="#2e3436"
#VIM_TERM_BG="#1e1e2e"
#VIM_TERM_BG="#000000"
#VIM_TERM_BG="#1c1c1c"

term_scheme() {
    local COLOR="$1" 
    if [ "$TERM" == "screen-256color" ]; then
        # TMUX
        echo -ne "\\ePtmux;\\e\\033]11;$COLOR\\007\\e\\\\"
    else
        #  NOT TMUX
        #echo -ne "\\033]11;$COLOR\\007"
        echo ""
    fi
}

#term_scheme $VIM_TERM_BG
#sleep 1
nvim "$@" 
#term_scheme $DEFAULT_TERM_BG

