#!/bin/sh
# source:
#   https://git.disroot.org/root_informatica/others/src/branch/master/qr.sh
# convert url to qr-code

set -eu

[ -z "${1:-}" ] && printf "usage: qr <url>" && exit 1

curl "qrenco.de/$1"

