#!/bin/sh

PICS_DIR="$HOME/stuff/pictures/screenshots"
PIC_FILE="$PICS_DIR/$(date +"%Y-%m-%d_%H-%M-%S").png"

[ -d "$PICS_DIR" ] || mkdir -p "$PICS_DIR" 

SCROT="scrot --file $PIC_FILE --quality 100 --silent"
OPTIONS="󰹑  screen\n  section\n  window\n"
SELECTOR="dmenu -c -l $(printf "%b" "$OPTIONS" | wc -l)"

RESULT="$(printf "%b" "$OPTIONS" | $SELECTOR)"
RESULT="${RESULT##* }"

[ -z "$RESULT" ] && exit

if [ "$RESULT" = "screen" ]; then
    sleep 0.25 && $SCROT && ( herbe "  screenshot" "saved, $PIC_FILE" &) &
elif [ "$RESULT" = "section" ]; then
    $SCROT --freeze --select --line "mode=edge,color=#007755,width=2" && \
        ( herbe "  screenshot" "saved, $PIC_FILE" & )
elif [ "$RESULT" = "window" ]; then
    WID=$(xdotool selectwindow)

    [ "$WID" ] && $SCROT --window "$WID" && \
        ( herbe "  screenshot" "saved, $PIC_FILE" & )
fi

