#!/bin/sh

set -eu

TODO_FILE="$(bfind .todo | head -n 1)"

superp_print() {
    printf "%b\n" "$(sed -e "s/\s\+$//" \
                         -e "/^\s*$/d" \
                         -e "s|^\(\s*\)\[[xX]\] \(.*\)$|\1  \\\e[0;2;9m \2 \\\e[0m|" \
                         -e "s|^\(\s*\)\[.\]|\1  |" \
                         -e "s|^\(\S.*\):|\\\e[1m\1\\\e[0m:|" "$1")"
}

[ -f "$TODO_FILE" ] && superp_print "$TODO_FILE" && exit 0

echo "todo: .todo file not found" 1>&2 && exit 1
