#!/bin/sh

set -eu

if [ "${1:-}" = "toggle" ]; then
    amixer set Master toggle
elif [ "${1:-}" = "up" ]; then
    amixer set Master 5%+
elif [ "${1:-}" = "down" ]; then
    amixer set Master 5%-
else
    echo "$(basename "${0:-volume}") toggle |> mute/unmute"
    echo "$(basename "${0:-volume}") up     |> +5% volume"
    echo "$(basename "${0:-volume}") down   |> -5% volume"
    exit
fi

pkill -USR1 -f "statusbar"
