#!/bin/sh
# Generates titles (79 chars wide) from either pipe or arguments, line by line:
# Usage:
#   - Piped input: cat title.txt | ./script.sh style_file mode
#   - Arguments: ./script.sh "Title Text" style mode
# Arguments:
#   $1: Display mode {0, 1, 2} (default is 0)

set -eu

mode="${1:-0}"
shift
if [ -t 0 ]; then
    cmd_='echo '${*:-}
else
    cmd_='cat'
fi

# sed magic
[ "$mode" = 0 ] && {
    $cmd_ | sed "s/^\s*//"
    exit 0
}; [ "$mode" = 1 ] && {
    $cmd_ | sed -e 's/^\s*//' | \
        sed ':a ; /^.\{79,\}$/{ n ; ba } ; s/^/ / ; s/$/ / ; ba'
    exit 0
}; [ "$mode" = 2 ] && {
    $cmd_ | sed -e 's/^\s*//' | \
        sed ':a ; /^.\{79,\}$/{ n ; ba } ; s/^/ / ; ba'
    exit 0
}

echo "Invalid mode: choose from {0, 1, 2}"
exit 1
