
# PS1 cool shit
change_term_name() {
    echo -ne "\033]0;$1\007";
}
parse_git_status() {
    [ -z "$(git status --porcelain 2> /dev/null)" ] && echo -n "" || echo -n "[+]"
}
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
location_privileges() {
    if [ -z "$(pwd | grep "$HOME")" ]; then
        sudo -nv 2> /dev/null && echo "1;94" || echo "1;31" 
    else
        echo "92"
    fi
}
# Cool fzf functions
N_PLACES=""
N_PLACES="$(fdfind . "$HOME/stuff/code" --max-depth 1 -t d -H)"
N_PLACES="$HOME/.config/bash\n$N_PLACES"
N_PLACES="$HOME/.config/nvim\n$N_PLACES"
N_PLACES="$HOME/.local/scripts\n$N_PLACES"
G_PLACES="$N_PLACES"
G_PLACES="$HOME/stuff\n$G_PLACES"
G_PLACES="$HOME/stuff/.dotfiles\n$G_PLACES"
G_PLACES="$HOME/stuff/Downloads\n$G_PLACES"
G_PLACES="$HOME/stuff/shit/magic_macro\n$G_PLACES"
G_PLACES="/var/backups/bacup\n$G_PLACES"
# go to path
function g_() {
    JUMP="$(echo -e "$G_PLACES" | sort -f | fzf --ansi --border=rounded --preview 'tree -m -p {} -y 64' --tiebreak=end)"

    if [ -d "$JUMP" ]; then
        cd "$JUMP"
        pwd
    fi
}
# nvim to path
function n_() {
    JUMP="$(echo -e "$N_PLACES" | sort -f | fzf --ansi --border=rounded --preview 'tree -m -p {} -y 64' --tiebreak=end)"

    if [ -d "$JUMP" ]; then
        cd "$JUMP"
        pwd
        nvim
    fi
}
# launch program
function l_() {
    PROGRAMS="firefox"
    PROGRAMS="nautilus\n$PROGRAMS"
    PROGRAMS="eclipse\n$PROGRAMS"

    SELECTED="$(echo -e "$PROGRAMS" | sort -f | fzf --ansi --border=rounded --tiebreak=begin)"

    if [ "$SELECTED" = "firefox" ]; then 
        firefox &> /dev/null & true
    elif [ "$SELECTED" = "nautilus" ]; then
        nautilus . &> /dev/null & true
    elif [ "$SELECTED" = "eclipse" ]; then
        $HOME/stuff/eclipse/eclipse/eclipse &> /dev/null & true
    else
        echo "not implemented yet."
    fi
}

# .bash_shortcuts generator
function g_alias() {
    echo "alias g_$1='cd $2 && pwd'" >> "$SHORTCUTS_FILE"
}
function n_alias() {
    echo "alias n_$1='cd $2 && pwd && nvim'" >> "$SHORTCUTS_FILE"
}

function bash_shortcut_gen() {
    SHORTCUTS_FILE="$HOME/.config/bash/.bash_shortcuts"
    # nvim ------------------------------------------------------------------
    echo -e "# file generated by '$(basename "$0")' - $(date +"%F %T")\n" > "$SHORTCUTS_FILE"

    for PLACE in $(echo -e "$N_PLACES")
    do
        ALIAS_NAME="$(echo "$PLACE" | sed "s|\/.*\/||")"

        n_alias "$ALIAS_NAME" "$PLACE"
    done

    # go --------------------------------------------------------------------
    for PLACE in $(echo -e "$G_PLACES")
    do
        ALIAS_NAME="$(echo "$PLACE" | sed "s|\/.*\/||")"

        g_alias "$ALIAS_NAME" "$PLACE"
    done

    notify-send --urgency=normal -t 1000 -i "terminal" "shortcut file updated ...ᘛ⁐̤ᕐᐷ"
}
# update shortcuts file
if [ ~/.config/bash/.bash_functions -nt ~/.config/bash/.bash_shortcuts ]; then
    bash_shortcut_gen
fi

unset -f bash_shortcut_gen
unset -f g_alias
unset -f n_alias
